### ISSUE TITLE
No macOS Support

### ISSUE THREAD

**Issue by cbyrneee** [lorenzofiamingo/SwiftUI-CachedAsyncImage#1]
When trying to use this dependency under macOS, the project fails to build.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/71222289/139504464-66958d47-6882-48c5-98ed-f167dbfdd53f.png">

**Comment by lorenzofiamingo** [comment]
Checkout the new [release](https://github.com/lorenzofiamingo/SwiftUI-CachedAsyncImage/releases/tag/1.1.0). Can you tell me if it works, I don't have the possibility to test on macOS 12.

**Comment by cbyrneee** [comment]
Yeah sure

**Comment by cbyrneee** [comment]
I'm experiencing some weird behaviour in a ``List``. When the view is first initialised, it will load fine. After I scroll down a few elements, a few of them seem to disappear and get stuck in an endless loading state. (my internet is bad however, so this 'endless loading' could just be it ignoring the cache for some reason)

This issue does not seem to appear on iOS.

https://user-images.githubusercontent.com/71222289/139528449-6f8611b6-5e59-48d0-ac0e-2f2469fc4849.mov

**Comment by cbyrneee** [comment]
Sometimes, it shows the image initially, but then decides to go into that loading state for all of them after scrolling a small bit
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/71222289/139528631-be8772bd-d877-41b0-9f7c-69a09bcf0a05.png">

**Comment by cbyrneee** [comment]
That being said, it appears to work perfectly outside of lists.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/71222289/139529007-814801b6-d0cc-4813-82de-ac684c8602f2.png">

**Comment by lorenzofiamingo** [comment]
Very strange that iOS and macOS behave differently, the only thing that comes to mind is that `URLCache.shared` has different sizes between iOS and macOS. Try using a custom `URLCache`:
```swift
CachedAsyncImage(url: logoURL, urlCache: .imageCache)
```

```swift
// URLCache+imageCache.swift

extension URLCache {
    
    static let imageCache = URLCache(memoryCapacity: 512*1000*1000, diskCapacity: 10*1000*1000*1000)
}

**Comment by lorenzofiamingo** [comment]
Can I see the code you are using for the `List`?

**Comment by cbyrneee** [comment]
Sure, here @lorenzofiamingo:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/71222289/139531754-eb132ab1-7c3f-4194-a775-903d9e38af49.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/71222289/139531757-71a64791-8eac-472c-943e-5866e190165d.png">

**Comment by lorenzofiamingo** [comment]
Also Track please :)

**Comment by cbyrneee** [comment]
@lorenzofiamingo Track.swift:
```

class Track: ObservableObject, Equatable, Identifiable {
    static func == (lhs: Track, rhs: Track) -> Bool {
        return lhs.name == rhs.name && lhs.artist == rhs.artist && lhs.albumArt == rhs.albumArt && lhs.playing == rhs.playing
    }

    @Published var name: String
    @Published var artist: String
    @Published var albumArt: URL?
    @Published var playing: Bool

    init(name: String, artist: String, albumArt: URL?, playing: Bool) {
        self.name = name
        self.artist = artist
        self.albumArt = albumArt
        self.playing = playing
    }
}```

**Comment by lorenzofiamingo** [comment]
The problem could be in the way you have implemented Identifiable, the task is linked to the view and the view is linked to the list by the ID of the tracks, so it could happen that multiple tasks are launched with the same ID and in this way they are overwritten before being completed.

**Comment by lorenzofiamingo** [comment]
Try adding to Task this: "var id: UUID { .init() }" and see if it works.

**Comment by lorenzofiamingo** [comment]
In any case, I recommend that you make Track a struct. In SwiftUI the best practice is to make your models value-type. What manages them (ViewModels) instead classes or actors.

**Comment by cbyrneee** [comment]
Alright, I'll try that now

**Comment by cbyrneee** [comment]
It doesn't seem to resolve the problem. I can't make ``Track`` a struct since I am inheriting ``ObservableObject``.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/71222289/139535125-91d0de9f-8856-4522-ab03-682e7e77e033.png">

**Comment by cbyrneee** [comment]
After a bit of refactoring, it appears to be working now

**Comment by cbyrneee** [comment]
However, when my list updates, it appears to break again. I need to look into this further, it's probably my problem.

**Comment by cbyrneee** [comment]
Alright, I have solved the problem. Thank you.

**Comment by lorenzofiamingo** [comment]
@cbyrneee What was the problem?

**Comment by cbyrneee** [comment]
@lorenzofiamingo my view was being updated too many times, presumably causing the URLCache / URLSession to get backlogged

**Comment by buzai** [comment]
@cbyrneee  how you fix URLSession?
