### ISSUE TITLE
Archive Failing

### ISSUE THREAD

**Issue by hobbesthetige** [lorenzofiamingo/SwiftUI-CachedAsyncImage#4]
Whenever I archive with your SPM it fails. I was doing a little reading into the matter, and it seems that you're missing some things in your Package.swift file that is causing the problem.

platforms: [
    .iOS(.v15)
],

**Comment by lorenzofiamingo** [comment]
Check the new [release](https://github.com/lorenzofiamingo/SwiftUI-CachedAsyncImage/releases/tag/1.3.0).

Please tell me if the error persists.
