### ISSUE TITLE
Is 404 counted as an error?

### ISSUE THREAD

**Issue by livid** [lorenzofiamingo/SwiftUI-CachedAsyncImage#5]
It seems after I switched from `AsyncImage` to your `CachedAsyncImage`, 404 is no longer an error. Thus when the code tried to load an URL that returned 404, the code would never reach `phase.error`, thus a placeholder is always showing.

**Comment by lorenzofiamingo** [comment]
Fixing this right now.

**Comment by livid** [comment]
During diagnosis, I also noticed if the remote URL has cacheable HTTP header settings:

- Cache-Control has positive max-age
- No Set-Cookie headers

Then AsyncImage will not send duplicate requests to the server.

**Comment by lorenzofiamingo** [comment]
Check the new [release](https://github.com/lorenzofiamingo/SwiftUI-CachedAsyncImage/releases/tag/1.4.0).

I tried to emulate the original Error as much as possible.

**Comment by lorenzofiamingo** [comment]
> During diagnosis, I also noticed if the remote URL has cacheable HTTP header settings:
> 
> * Cache-Control has positive max-age
> * No Set-Cookie headers
> 
> Then AsyncImage will not send duplicate requests to the server.

Make a pull request if you want to.
