### ISSUE TITLE
[boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics

### ISSUE THREAD

**Issue by Djibs** [lorenzofiamingo/SwiftUI-CachedAsyncImage#9]
Hello

Every time an image is loaded I have this message appearing in the Xcode logs. 

If it is already cached, the message will not appear.

![DJIBS 2022-02-24 à 18 56 36](https://user-images.githubusercontent.com/1236842/155580447-2df01af0-7106-44db-9d21-49f2786a6edd.jpg)

**Comment by lorenzofiamingo** [comment]
This warning is generated in this system method:
```swift
let (data, response) = try await data(for: request, delegate: controller)
```
I cannot do anything about this. Anyway this is not happening on physical devices

**Comment by Djibs** [comment]
okay, thank you
